# Site settings
title: 'Jonathan Martel'
email: jmartel@cmaisonneuve.qc.ca
description: > # this means to ignore newlines until "baseurl:"
  Articles on JavaScript, Angular, React and HTML5 (based on Todd Motto.com)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonathanmartel.github.io" # the base hostname & protocol for your site
twitter_username: jonmartel
github_username:  jonathanmartel
include: ['_pages']
exclude: ['node_modules', '_site']
paginate: 11
paginate_path: "/page:num/"
permalink: pretty 
sass:
  compressed: true

collections:
  note_javascript:
    output: true
    sort_by: order

# Build settings
markdown: kramdown
highlighter: rouge



# Gems
plugins: [jekyll-paginate]


kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

