# Site settings
title: 'Jonathan Martel'
email: jmartel@cmaisonneuve.qc.ca
description: > # this means to ignore newlines until "baseurl:"
  Articles on JavaScript, Angular, React and HTML5 (based on Todd Motto.com)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonathanmartel.github.io" # the base hostname & protocol for your site
twitter_username: jonmartel
github_username:  jonathanmartel
include: [_pages]
exclude: ['node_modules']
paginate: 11
paginate_path: "/page:num/"
permalink: /:year/:month/:title
sass:
  compressed: true

# Build settings
markdown: kramdown
highlighter: rouge

# Gems
gems: [jekyll-paginate]
